name: Run Unit Tests

## when a push is made to unit Test branch (update this later to be main), run out unit tests.
## Ideally this is on a pullrequest to main
on: 
  push:
    branches:
      - unitTests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout working branch
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Sanity Check
      run: echo "Made it!"